---
- name: Add mopidy APT repo signing key
  apt_key:
      url: https://apt.mopidy.com/mopidy.gpg
      state: present
- name: Add mopidy APT repo
  apt_repository:
      repo: deb http://apt.mopidy.com/ stretch main contrib non-free
      state: present
- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      - mopidy
      - mopidy-spotify
      - mopidy-local-sqlite
      - python-pip
  notify: restart mopidy
- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items:
      - Mopidy-Iris
- name: Update mopidy config
  template:
      src: mopidy.conf
      dest: /etc/mopidy/mopidy.conf
      mode: 0640
  notify: restart mopidy
- name: Start mopidy on boot
  service: name=mopidy enabled=true
