---
- name: Install nginx
  apt: name=nginx state=installed
  # APT attempts to start the service for some reason, which crashes under Qemu because it tries to use IPv6 which we
  # haven't got set up
  ignore_errors: True
- name: Configure nginx
  template:
      src: nginx.conf
      dest: /etc/nginx/sites-enabled/default
- name: Start nginx on boot
  service:
      name: nginx
      state: restarted
      enabled: true
