---
- name: Install nginx
  apt: name=nginx update_cache=yes state=installed
  notify: restart nginx
  # APT attempts to start the service for some reason, which crashes under Qemu because it tries to use IPv6 which we
  # haven't got set up
  ignore_errors: True
- name: Configure nginx
  template:
      src: nginx.conf
      dest: /etc/nginx/sites-enabled/default
  notify: restart nginx
- name: Start nginx on boot
  service: name=nginx enabled=true
